services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.20.0
    volumes:
      - /films/Films/audiobooks:/audiobooks
      - /films/audiobookshelf/config:/config
      - /films/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Paris
    networks:
      - nas
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.fgdou.ovh`)'
      - 'traefik.http.routers.audiobookshelf.entryPoints=websecure'
      - 'traefik.http.services.audiobookshelf.loadbalancer.server.port=80'

networks:
  nas:
    external: true

