services:
  ciq-wordpress:
    image: wordpress
    restart: always
    volumes:
      - /data/ciq/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ciq-mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - ciq-mysql
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ciq-wordpress.rule=Host(`ciq-panier.fr`)'
      - 'traefik.http.routers.ciq-wordpress.entryPoints=websecure'
      - 'traefik.http.services.ciq-wordpress.loadbalancer.server.port=80'
    networks:
      - ciq
      - nas
  ciq-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - /data/ciq/mysql:/var/lib/mysql
    networks:
      - ciq
  ciq-postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=authentik
    volumes:
      - /data/ciq/postgres:/var/lib/postgresql/data
    networks:
      - ciq
  ciq-authentik:
    image: ghcr.io/goauthentik/server:2025.10.3
    restart: always
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: ciq-redis
      AUTHENTIK_POSTGRESQL__HOST: ciq-postgres
      AUTHENTIK_POSTGRESQL__USER: user
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: password
      AUTHENTIK_SECRET_KEY: ${CIQ_AUTHENTIK_SECRET_KEY}
      TZ: Europe/Paris
    volumes:
      - /data/ciq/authentik/media:/media
      - /data/ciq/authentik/custom-templates:/templates
    networks:
      - ciq
      - nas
    depends_on:
      - ciq-postgres
      - ciq-redis
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ciq-authentik.rule=Host(`auth.ciq-panier.fr`)'
      - 'traefik.http.routers.ciq-authentik.entryPoints=websecure'
      - 'traefik.http.services.ciq-authentik.loadbalancer.server.port=9000'
  ciq-authentik-worker:
    image: ghcr.io/goauthentik/server:2025.10.3
    restart: unless-stopped
    command: worker
    networks:
      - ciq
    environment:
      AUTHENTIK_REDIS__HOST: ciq-redis
      AUTHENTIK_POSTGRESQL__HOST: ciq-postgres
      AUTHENTIK_POSTGRESQL__USER: user
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: password
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/ciq/authentik/media:/media
      - /data/ciq/authentik/certs:/certs
      - /data/ciq/authentik/custom-templates:/templates
    depends_on:
      - ciq-postgres
      - ciq-redis
  ciq-redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - /data/ciq/authentik/redis:/data
    networks:
      - ciq
  ciq-adminer:
    image: adminer
    networks:
      - nas
      - ciq
  ciq-ddclient:
    image: lscr.io/linuxserver/ddclient:3.11.2
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
    volumes:
      - /data/ciq/ddclient:/config
    restart: always

networks:
  ciq:
  nas:
    external: true
