
services:
  dawarich_redis:
    image: redis:7.4-alpine
    container_name: dawarich_redis
    command: redis-server
    networks:
      - dawarich
    volumes:
      - /data/dawarich/shared:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    # image: imresamu/postgis:17-3.5-alpine # If you're on ARM architecture, use this image instead
    shm_size: 1G
    container_name: dawarich_db
    volumes:
      - /data/dawarich/db_data:/var/lib/postgresql/data
      - /data/dawarich/shared:/var/shared
    networks:
      - dawarich
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-dawarich_development}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-dawarich_development}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use custom config, uncomment if you want to use a custom config

  dawarich_app:
    image: freikin/dawarich:0.36.3
    container_name: dawarich_app
    volumes:
      - /data/dawarich/public:/var/app/public
      - /data/dawarich/watched:/var/app/tmp/imports/watched
      - /data/dawarich/storage:/var/app/storage
      - /data/dawarich/db_data:/dawarich_db_data
    networks:
      - dawarich
      - nas
        #ports:
      #- "${DAWARICH_APP_PORT:-3000}:3000"
      # - "${PROMETHEUS_PORT:-9394}:9394" # Prometheus exporter, uncomment if needed
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      TZ: Europe/Paris
      RAILS_ENV: ${RAILS_ENV:-production}
      REDIS_URL: ${REDIS_URL:-redis://dawarich_redis:6379}
      DATABASE_HOST: ${DATABASE_HOST:-dawarich_db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_NAME: ${DATABASE_NAME:-dawarich_development}
      MIN_MINUTES_SPENT_IN_CITY: ${MIN_MINUTES_SPENT_IN_CITY:-60}
      APPLICATION_HOSTS: ${APPLICATION_HOSTS:-localhost,::1,127.0.0.1,dawarich.fgdou.ovh,auth.fgdou.ovh}
      TIME_ZONE: ${TIME_ZONE:-Europe/London}
      APPLICATION_PROTOCOL: ${APPLICATION_PROTOCOL:-http}
      PROMETHEUS_EXPORTER_ENABLED: ${PROMETHEUS_EXPORTER_ENABLED:-false}
      PROMETHEUS_EXPORTER_HOST: ${PROMETHEUS_EXPORTER_HOST:-0.0.0.0}
      PROMETHEUS_EXPORTER_PORT: ${PROMETHEUS_EXPORTER_PORT:-9394}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-"CHANGE_ME"}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT:-true}
      SELF_HOSTED: ${SELF_HOSTED:-true}
      STORE_GEODATA: ${STORE_GEODATA:-true} 
      OIDC_ISSUER: https://auth.fgdou.ovh/application/o/dawarich/
      OIDC_CLIENT_ID: b4nORfYgQkhay8kMsudgUAZwAnxhKS51v2BjPMAy
      OIDC_CLIENT_SECRET: ${DAWARICH_OIDC_SECRET}
      OIDC_REDIRECT_URI: https://dawarich.fgdou.ovh/users/auth/openid_connect/callback 
      OIDC_AUTO_REGISTER: true
      OIDC_PROVIDER_NAME: Authentik
      ALLOW_EMAIL_PASSWORD_REGISTRATION: false
    logging:
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE:-100m}
        max-file: ${LOG_MAX_FILE:-5}
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: ${APP_CPU_LIMIT:-0.50}
          memory: ${APP_MEMORY_LIMIT:-4G}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dawarich.rule=Host(`dawarich.fgdou.ovh`)'
      - 'traefik.http.routers.dawarich.entryPoints=websecure'
      - 'traefik.http.services.dawarich.loadbalancer.server.port=3000'

  dawarich_sidekiq:
    image: freikin/dawarich:0.36.3
    container_name: dawarich_sidekiq
    volumes:
      - /data/dawarich/public:/var/app/public
      - /data/dawarich/watched:/var/app/tmp/imports/watched
      - /data/dawarich/storage:/var/app/storage
    networks:
      - dawarich
    stdin_open: true
    tty: true
    entrypoint: sidekiq-entrypoint.sh
    command: ['sidekiq']
    restart: on-failure
    environment:
      TZ: Europe/Paris
      RAILS_ENV: ${RAILS_ENV:-production}
      REDIS_URL: ${REDIS_URL:-redis://dawarich_redis:6379}
      DATABASE_HOST: ${DATABASE_HOST:-dawarich_db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_NAME: ${DATABASE_NAME:-dawarich_development}
      APPLICATION_HOSTS: ${APPLICATION_HOSTS:-localhost,::1,127.0.0.1,dawarich.fgdou.ovh,auth.fgdou.ovh}
      BACKGROUND_PROCESSING_CONCURRENCY: ${BACKGROUND_PROCESSING_CONCURRENCY:-10}
      APPLICATION_PROTOCOL: ${APPLICATION_PROTOCOL:-http}
      PROMETHEUS_EXPORTER_ENABLED: ${PROMETHEUS_EXPORTER_ENABLED:-false}
      PROMETHEUS_EXPORTER_HOST: ${PROMETHEUS_EXPORTER_HOST_SIDEKIQ:-dawarich_app}
      PROMETHEUS_EXPORTER_PORT: ${PROMETHEUS_EXPORTER_PORT:-9394}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-"CHANGE_ME"}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT:-true}
      SELF_HOSTED: ${SELF_HOSTED:-true}
      STORE_GEODATA: ${STORE_GEODATA:-true}
      OIDC_ISSUER: https://auth.fgdou.ovh/application/o/dawarich/
      OIDC_CLIENT_ID: b4nORfYgQkhay8kMsudgUAZwAnxhKS51v2BjPMAy
      OIDC_CLIENT_SECRET: ${DAWARICH_OIDC_SECRET}
      OIDC_REDIRECT_URI: https://dawarich.fgdou.ovh/users/auth/openid_connect/callback 
      OIDC_AUTO_REGISTER: true
      ALLOW_EMAIL_PASSWORD_REGISTRATION: false
    logging:
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE:-100m}
        max-file: ${LOG_MAX_FILE:-5}
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f sidekiq" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
        restart: true
      dawarich_redis:
        condition: service_healthy
        restart: true
      dawarich_app:
        condition: service_healthy
        restart: true

networks:
  nas:
    external: true
  dawarich:

