services:
  defguard_core:
    image: ghcr.io/defguard/defguard:latest
    environment:
      DEFGUARD_COOKIE_INSECURE: "true"
      DEFGUARD_SECRET_KEY: aa5a506b11d719dd7170f57f5d9947faf8eb0bc2be1325e42aa0237c3dcfd26456e73dff9eef3b12c7bcf8711b45e3e703d8e21ee1c08520f5e12e3f5772da94
      DEFGUARD_AUTH_SECRET: defguard-auth-secret
      DEFGUARD_GATEWAY_SECRET: defguard-gateway-secret
      DEFGUARD_YUBIBRIDGE_SECRET: defguard-yubibridge-secret
      DEFGUARD_DB_HOST: defguard_db
      DEFGUARD_DB_PORT: 5432
      DEFGUARD_DB_USER: defguard
      DEFGUARD_DB_PASSWORD: defguard
      DEFGUARD_DB_NAME: defguard
      DEFGUARD_URL: https://defguard.fgdou.ovh
      RUST_BACKTRACE: 1
        #ports:
      # rest api
      #- "8000:8000"
      # grpc
      #- "50055:50055"
    depends_on:
      - defguard_db
    networks:
      - nas
      - defguard
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.defguard.rule=Host(`defguard.fgdou.ovh`)'
      - 'traefik.http.routers.defguard.entryPoints=websecure'
      - 'traefik.http.services.defguard.loadbalancer.server.port=8000'

  defguard_gateway:
    image: ghcr.io/defguard/gateway:latest
    environment:
      DEFGUARD_GRPC_URL: http://defguard_core:50055
      DEFGUARD_STATS_PERIOD: 60
      DEFGUARD_TOKEN: BIU6wict1FwOCrx1N91a4uTafWgJme7V
      RUST_LOG: debug
        #ports:
      # WireGuard endpoint
      #- "50051:50051/udp"
    depends_on:
      - defguard_core
    cap_add:
      - NET_ADMIN
    networks:
      - defguard

  defguard_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: defguard
      POSTGRES_USER: defguard
      POSTGRES_PASSWORD: defguard
    volumes:
      - /data/defguard/db:/var/lib/postgresql/data
        #ports:
        #- "5432:5432"
    networks:
      - defguard

networks:
  nas:
    external: true
  defguard:
