services:
  dumbassets:
    container_name: dumbassets
    image: dumbwareio/dumbassets:1.0.11
    networks:
      - nas
    volumes:
      - /data/dumbassets:/app/data
    restart: unless-stopped
    environment:
      PORT: ${DUMBASSETS_PORT:-3000}
      NODE_ENV: ${DUMBASSETS_NODE_ENV:-production}
      DEBUG: ${DUMBASSETS_DEBUG:-true}
      SITE_TITLE: ${DUMBASSETS_SITE_TITLE:-DumbAssets}
      BASE_URL: ${DUMBASSETS_BASE_URL:-https://dumbassets.fgdou.ovh}
      DUMBASSETS_PIN: ${DUMBASSETS_PIN:-}
      ALLOWED_ORIGINS: ${DUMBASSETS_ALLOWED_ORIGINS:-*}
      APPRISE_URL: ${DUMBASSETS_APPRISE_URL:-}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dumbassets.rule=Host(`dumbassets.fgdou.ovh`)'
      - 'traefik.http.routers.dumbassets.entryPoints=websecure'
      - 'traefik.http.services.dumbassets.loadbalancer.server.port=3000'
      - 'traefik.http.services.dumbassets.middlewares=authentik@docker'
networks:
  nas:
    external: true
