services:
  endurain:
    container_name: endurain-app
    image: ghcr.io/endurain-project/endurain:v0.16.4
    volumes:
    #  - <local_path>/endurain/backend/app:/app/backend # Configure volume if you want to edit the code locally by cloning the repo
      - /data/endurain/backend/data:/app/backend/data # necessary for activity files, user images and server images persistence on container image updates
      - /data/endurain/backend/logs:/app/backend/logs # log files for the backend
        #ports:
        #- "8080:8080"
    depends_on:
      endurain_postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nas
      - endurain
    environment:
      DB_PASSWORD: password
      SECRET_KEY: ${ENDURAIN_SECRET}
      FERNET_KEY: ${ENDURAIN_FERNET}
      ENDURAIN_HOST: https://endurain.fgdou.ovh
      BEHIND_PROXY: true
      DB_HOST: endurain_postgres
    labels:
      - 'traefik.enable=true' 
      - 'traefik.http.routers.endurain.rule=Host(`endurain.fgdou.ovh`)'
      - 'traefik.http.routers.endurain.entryPoints=websecure'
      - 'traefik.http.services.endurain.loadbalancer.server.port=8080'

   # postgres logic
  endurain_postgres:
    image: docker.io/postgres:17.5
    container_name: endurain-postgres
    environment:
      POSTGRES_PASSWORD: password
      TZ: Europe/Paris
      POSTGRES_DB: endurain
      POSTGRES_USER: endurain
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U endurain"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /data/endurain/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - endurain

networks:
  endurain:
  nas:
    external: true
