services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.12
    volumes:
      - /data/Homeassistant/core:/config
      - /etc/localtime:/etc/localtime:ro
      - /data/Homeassistant/media:/media
      - /run/dbus:/run/dbus
    restart: unless-stopped
    privileged: true
    #ports:
    #  - 8123:8123
    user: "root:users"
      #devices:
      #- /dev/ttyACM0:/dev/ttyACM0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homeassistant.rule=Host(`dash.fgdou.ovh`)'
      - 'traefik.http.routers.homeassistant.entryPoints=websecure'
      - 'traefik.http.services.homeassistant.loadbalancer.server.port=8123'
    networks:
      - nas
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:2.7.1
    restart: unless-stopped
    volumes:
        - /data/Homeassistant/zigbee2mqtt:/app/data
        - /run/udev:/run/udev:ro
          # ports:
        # Frontend port
        #- 8080:8080
    environment:
        - TZ=Europe/Berlin
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.fgdou.ovh`)'
      - 'traefik.http.routers.zigbee2mqtt.entryPoints=websecure'
      - 'traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080'
      - 'traefik.http.routers.zigbee2mqtt.middlewares=authentik@docker'
  mosquitto:
    image: eclipse-mosquitto:2.0.22
    volumes:
      - /data/Homeassistant/mosquitto/config:/mosquitto/config
      - /data/Homeassistant/mosquitto/data:/mosquitto/data
    restart: unless-stopped
      #ports:
      #- 1883:1883
    networks:
      - nas  
  musicassistant:
    container_name: musicassistant
    image: ghcr.io/music-assistant/server:latest
    restart: unless-stopped
    volumes:
      - /data/Homeassistant/musicassistant
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=warning
    networks:
      - nas
    ports:
      - 8098:8098
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.musicassistant.rule=Host(`musicassistant.fgdou.ovh`)'
      - 'traefik.http.routers.musicassistant.entryPoints=websecure'
      - 'traefik.http.services.musicassistant.loadbalancer.server.port=8095'

networks:
  nas:
    external: true
