services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.9
    volumes:
      - /data/Homeassistant/core:/config
      - /etc/localtime:/etc/localtime:ro
      - /data/Homeassistant/media:/media
      - /run/dbus:/run/dbus
    restart: unless-stopped
    privileged: true
    network_mode: host
    #ports:
    #  - 8123:8123
    user: "root:users"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network='
networks:
  nas:
    external: true
