services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:14.0.0
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.fgdou.ovh
      # env_file: mailserver.env
    environment:
      DMS_DEBUG: info
      SSL_TYPE: letsencrypt
      SSL_DOMAIN: fgdou.ovh
      RELAY_HOST: in-v3.mailjet.com
      RELAY_PORT: 587
      RELAY_USER: ${MAILJET_EMAIL}
      RELAY_PASSWORD: ${MAILJET_PASSWORD}
    dns:
      - 8.8.8.8
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /data/mail/mail-data/:/var/mail/
      - /data/mail/mail-state/:/var/mail-state/
      - /data/mail/mail-logs/:/var/log/mail/
      - /data/mail/config/:/tmp/docker-mailserver/
      - /data/traefik/acme.json:/etc/letsencrypt/acme.json:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
