services:
  matrix:
    image: matrixdotorg/synapse:v1.138.2
    restart: unless-stopped
    volumes:
      - /data/matrix:/data
      #- ./tuwunel.toml:/etc/tuwunel.toml
    networks:
      - nas
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_SERVER_NAME=matrix.fgdou.ovh

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.matrix.rule=Host(`matrix.fgdou.ovh`)'
      - 'traefik.http.routers.matrix.entryPoints=websecure'
      - 'traefik.http.services.matrix.loadbalancer.server.port=8008'


  element:
    image: vectorim/element-web:v1.12.0
    restart: unless-stopped
    volumes:
         - /data/element/config.json:/app/config.json
    networks:
         - nas
    depends_on:
        - matrix
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.element.rule=Host(`element.fgdou.ovh`)'
      - 'traefik.http.routers.element.entryPoints=websecure'
      - 'traefik.http.services.element.loadbalancer.server.port=80'

networks:
  nas:
    external: true
