services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.1.1
    container_name: mealie
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /data/maelie:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.fgdou.ovh
      - SMTP_HOST=mail.fgdou.ovh
      - SMTP_FROM_EMAIL=no-reply@fgdou.ovh
      - SMTP_USER=no-reply@fgdou.ovh
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_AUTH_STRATEGY=TLS
      - OIDC_AUTH_ENABLED=true
      - OIDC_CONFIGURATION_URL=https://auth.fgdou.ovh/application/o/mealie/.well-known/openid-configuration
      - OIDC_CLIENT_ID=E9KSp7i2gahMqkkdvQalGBb8AWVZR5k26a9HNf5P
      - OIDC_CLIENT_SECRET=${AUTHENTIK_MEALIE_SECRET}
      - OIDC_AUTO_REDIRECT=true
      - OIDC_PROVIDER_NAME=SSO
      - OIDC_ADMIN_GROUP=admin
      - OIDC_USER_CLAIM=sub
    restart: always
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mealie.rule=Host(`mealie.fgdou.ovh`)'
      - 'traefik.http.routers.mealie.entryPoints=websecure'
      - 'traefik.http.services.mealie.loadbalancer.server.port=9000'

networks:
  nas:
    external: true
