volumes:
  prometheus_data: {}

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.10.2
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
        #- '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

  blackbox:
    image: quay.io/prometheus/blackbox-exporter:v0.28.0
    networks:
      - monitoring
      - nas
    dns:
      - 1.1.1.1
    restart: always

  json_exporter:
    image: prometheuscommunity/json-exporter:v0.7.0
    restart: always
    networks:
      - monitoring
      - nas
    volumes:
      - /data/monitoring/json_exporter:/config:ro
    command:
      - '--config.file=/config/config.yml'

  jellyfin_exporter:
    image: rebelcore/jellyfin-exporter:latest
    container_name: jellyfin_exporter
    command:
      - '--jellyfin.address=http://jellyfin:8096'
      - '--jellyfin.token=${JELLYFIN_EXPORTER_API_KEY}'
    restart: unless-stopped
    networks:
      - monitoring
      - nas

  s3_exporter:
    image: ribbybibby/s3-exporter:v0.5.0
    restart: always
    networks:
      - monitoring
    environment:
      - AWS_ACCESS_KEY_ID=a7586b3e917c4addba864b7015a8a98c
      - AWS_SECRET_ACCESS_KEY=${RESTIC_AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=gra
    command: "--s3.endpoint-url 'https://s3.gra.io.cloud.ovh.net/'"

  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /data/monitoring/prometheus:/prometheus
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=60d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - monitoring
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.fgdou.ovh`)'
      - 'traefik.http.routers.prometheus.entryPoints=websecure'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'
      - 'traefik.http.routers.prometheus.middlewares=authentik@docker'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    restart: unless-stopped
    userns_mode: "host"
    networks:
      - monitoring
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/lib/docker:/var/lib/docker:ro
      - /dev:/dev:ro
      - /sys:/sys:ro
    devices:
      - /dev/kmsg


  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    restart: unless-stopped
    volumes:
      - /data/monitoring/grafana:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: https://grafana.fgdou.ovh/
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "5Geuv1IQuwh222mjR9pHNTh70LK8InMLIwKasVCH"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${AUTHENTIK_GRAFANA_SECRET}
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.fgdou.ovh/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.fgdou.ovh/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.fgdou.ovh/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.fgdou.ovh/application/o/grafana/end-session/"
      # Optionally enable auto-login (bypasses Grafana login screen)
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      # Optionally map user groups to Grafana roles
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'admin') && 'Admin' || 'Viewer'"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "mail.fgdou.ovh:465"
      GF_SMTP_USER: "no-reply@fgdou.ovh"
      GF_SMTP_PASSWORD: ${SMTP_PASSWORD}
      GF_SMTP_FROM_ADDRESS: "no-reply@fgdou.ovh"
      GF_SMTP_FROM_NAME: "Grafana"

    networks:
      - nas
      - monitoring
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.fgdou.ovh`)'
      - 'traefik.http.routers.grafana.entryPoints=websecure'
      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'


  ntfy:
    image: binwiederhier/ntfy:v2.15.0
    container_name: ntfy
    environment:
      NTFY_BASE_URL: https://ntfy.fgdou.ovh
      NTFY_BEHIND_PROXY: true
    command:
      - serve
    volumes:
      - /data/monitoring/ntfy:/etc/ntfy
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ntfy.rule=Host(`ntfy.fgdou.ovh`)'
      - 'traefik.http.routers.ntfy.entryPoints=websecure'
      - 'traefik.http.services.ntfy.loadbalancer.server.port=80'
        #- 'traefik.http.routers.ntfy.middlewares=authentik@docker'
    networks:
      - nas
      - monitoring

networks:
  nas:
    external: true
  monitoring:
