services:
  nextcloud:
    networks:
      - nas
      - nextcloud
    image: nextcloud:30.0.5
    volumes:
      - /data/nextcloud/code:/var/www/html
    environment:
      - APACHE_DISABLE_REWRITE_IP=true
      - TRUSTED_PROXIES=10.0.0.0/8 172.16.0.0/8
      - OVERWRITEHOST=nextcloud.fgdou.ovh
      - OVERWRITEPROTOCOL=https
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=nextcloud_db
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
      - REDIS_HOST=nextcloud_redis
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextcloud.rule=Host(`nextcloud.fgdou.ovh`)'
      - 'traefik.http.routers.nextcloud.entryPoints=websecure'
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'
    healthcheck:
          test: curl --fail http://localhost:80/ || exit 1
          interval: 40s
          timeout: 30s
          retries: 3
          start_period: 60s
  nextcloud_redis:
    image: redis:7.4.0
    networks:
      - nextcloud
  nextcloud_db:
    image: postgres:16.1
    container_name: nextcloud_db
    volumes:
      - /data/nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=nextcloud
    networks:
      - nextcloud
    restart: unless-stopped

networks:
  nas:
    external: true
  nextcloud:
