services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=Europe/London
    volumes:
      - /films/Radarr:/config
      - /films/Films/films:/movies #optional
      - /films/Films/Download:/downloads #optional
    restart: unless-stopped
    networks:
      - nas
    depends_on:
      - prowlarr
      - qbittorrent
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.radarr.rule=Host(`radarr.fgdou.ovh`)'
      - 'traefik.http.routers.radarr.entryPoints=websecure'
      - 'traefik.http.services.radarr.loadbalancer.server.port=7878'
      - 'traefik.http.routers.radarr.middlewares=authentik@docker'

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=Europe/London
    volumes:
      - /films/Sonarr:/config
      - /films/Films/series:/tv #optional
      - /films/Films/Download:/downloads #optional
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - prowlarr
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sonarr.rule=Host(`sonarr.fgdou.ovh`)'
      - 'traefik.http.routers.sonarr.entryPoints=websecure'
      - 'traefik.http.services.sonarr.loadbalancer.server.port=8989'
      - 'traefik.http.routers.sonarr.middlewares=authentik@docker'

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - TZ=Europe/Paris
    volumes:
      - /films/prowlarr:/config
    restart: unless-stopped
    networks:
      - nas
      - torrent
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prowlarr.rule=Host(`prowlarr.fgdou.ovh`)'
      - 'traefik.http.routers.prowlarr.entryPoints=websecure'
      - 'traefik.http.services.prowlarr.loadbalancer.server.port=9696'
      - 'traefik.http.routers.prowlarr.middlewares=authentik@docker'


  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    restart: unless-stopped
    networks:
      - torrent

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
    volumes:
      - /films/jellyseerr:/app/config
    restart: unless-stopped
    dns:
      - 1.1.1.1
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.fgdou.ovh`)'
      - 'traefik.http.routers.jellyseerr.entryPoints=websecure'
      - 'traefik.http.services.jellyseerr.loadbalancer.server.port=5055'

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /films/qbittorrent:/config
      - /films/Films/Download:/downloads #optional
        #ports:
      #- 6881:6881
      #- 6881:6881/udp
    restart: unless-stopped
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.fgdou.ovh`)'
      - 'traefik.http.routers.qbittorrent.entryPoints=websecure'
      - 'traefik.http.services.qbittorrent.loadbalancer.server.port=8080'
      - 'traefik.http.routers.qbittorrent.middlewares=authentik@docker'

networks:
  nas:
    external: true
  torrent:
