services:

  VaultWarden:
    image: vaultwarden/server:1.32.3
    restart: always
    user: "root:users"
    volumes:
      - /data/VaultWarden:/data/
    environment:
            - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.fgdou.ovh`)'
      - 'traefik.http.routers.vaultwarden.entryPoints=websecure'
      - 'traefik.http.services.vaultwarden.loadbalancer.server.port=80'

networks:
  nas:
    external: true
